#lang racket

(define (fill-vector v i)
    (define (iter v)
        (printf "enter number: ")
        (vector-set! v i (string->number (read-line)))
        (fill-vector v (+ i 1)))
    (if (<= i (- (vector-length v) 1)) 
        (iter v)
        v))

(define (get-biggest-i vec)
    (define (iter next-i biggest-at-i)
        (if (= next-i (vector-length vec)) biggest-at-i 
            (compare next-i biggest-at-i)))
    (define (compare i j)
        (if (> (vector-ref vec i) (vector-ref vec j))
            (iter (+ i 1) i)
            (iter (+ i 1) j)))
    (compare 0 0))
    
(define (max-pairwise-product vec)
    (define first-max-index (get-biggest-i vec))
    (printf (number->string (vector-ref vec first-max-index)))
    ;(printf (number->string first-max-index))
    (printf " * ")
    (define lst (if (> (vector-length vec) 1)
                    (remove (vector-ref vec first-max-index) (vector->list vec))
                    (vector->list vec)))
    (define second-vec (list->vector lst)) 
    (define second-max-index (get-biggest-i second-vec))
    (printf (number->string (vector-ref second-vec second-max-index)))
    ;(printf (number->string second-max-index))
    (printf " = ")
    (* (vector-ref vec first-max-index) (vector-ref second-vec second-max-index)))

(printf "Enter vector length: ")
(define vec-len (read-line))
(define vec (make-vector (string->number vec-len)))
(fill-vector vec 0)
(max-pairwise-product vec)
